config/routes.rb
Bozo::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  root :to => "dashboard#index"
  
  resources :users
  resources :articles
  resources :categories
  
  resources :stats do 
    collection do
      get :incoming_by_day
      get :closed_by_day
      get :incoming_by_hour
      get :close_time_by_day
    end
  end

  resource :dashboard, :controller => 'dashboard' do
    collection do
      get :byuser
    end
  end     

end # of routes

app/models/user.rb
#
#
#
class User
  include MongoMapper::Document  
  plugin MongoMapper::Devise
    
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
    
  # Attributes
  key :email,                 String
  key :encrypted_password,    String
  key :password_salt,         String
  key :reset_password_token,  String
  key :remember_token,        String
  key :remember_created_at,   Time
  key :sign_in_count,         Integer
  key :current_sign_in_at,    Time
  key :last_sign_in_at,       Time
  key :current_sign_in_ip,    String
  key :last_sign_in_ip,       String
  key :email_alert,           Boolean
  key :sms_alert,             Boolean
  key :weekend,               Boolean
  key :estime,                Time
  key :eetime,                Time
  key :sstime,                Time
  key :setime,                Time
  key :nick,                  String
  key :sms_address,           String
  timestamps!
  
  # Validations
  REG_EMAIL_NAME   = '[\w\.%\+\-]+'
  REG_DOMAIN_HEAD  = '(?:[A-Z0-9\-]+\.)+'
  REG_DOMAIN_TLD   = '(?:[A-Z]{2}|com|org|net|gov|mil|biz|info)'
  REG_EMAIL_OK     = /\A#{REG_EMAIL_NAME}@#{REG_DOMAIN_HEAD}#{REG_DOMAIN_TLD}\z/i
  
  validates_length_of :email, :within => 6..100, :allow_blank => true
#  validates_format_of :email, :with => REG_EMAIL_OK, :allow_blank => true
  
end # of class

app/controllers/users_controller.rb
#
#
#
class UsersController < ApplicationController
  
  before_filter :authenticate_user!
  
  #
  # GET /users
  # GET /users.xml
  #
  def index
    @users = User.all(:order => "nick, id ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  
  #
  # GET /users/1
  # GET /users/1.xml
  #
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  
  #
  # GET /users/new
  # GET /users/new.xml
  #
  def new
  end

  
  #
  # GET /users/1/edit
  #
  def edit
    @user = User.find(params[:id])
  end

  
  #
  # POST /users
  # POST /users.xml
  #
  def create
  end

  
  #
  # PUT /users/1
  # PUT /users/1.xml
  #
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      @user.email       = params[:user][:email]
      @user.nick        = params[:user][:nick]
      @user.email_alert = params[:user][:email_alert]
      @user.estime      = params[:user][:estime]
      @user.eetime      = params[:user][:eetime]
      @user.sms_alert   = params[:user][:sms_alert]
      @user.sms_address = params[:user][:sms_address]
      @user.sstime      = params[:user][:sstime]
      @user.setime      = params[:user][:setime]
      @user.weekend     = params[:user][:weekend]

      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => "User was successfully updated.") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  
  #
  # DELETE /users/1
  # DELETE /users/1.xml
  #
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  
end # of class

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style=" ">
    <table class="simple-nb">
      <tr>
        <td><%= f.label :nick %></td>
        <td><%= f.text_field :nick %></td>
      </tr>
      <tr>
        <td><%= f.label :email %></td>
        <td><%= f.text_field :email %></td>
      </tr>
      <tr>
        <td colspan="2"><hr style="margin:5px 0"/></td>
      </tr>
      <tr>
        <td><%= f.label 'Email alert' %></td>
        <td><%= f.check_box :email_alert %></td>
      </tr>
      <tr>
        <td><%= f.label 'Start time' %></td>
        <td>
          <%= text_field_tag "user[estime]", @user.estime && l(@user.estime, :format => :default), :size => 8 %>
          <span class="hint">(e.g. 9:00 am)</span>
        </td>
      </tr>
      <tr>
        <td><%= f.label 'End time' %></td>
        <td>
          <%= text_field_tag "user[eetime]", @user.eetime && l(@user.eetime, :format => :default), :size => 8 %>
          <span class="hint">(e.g. 6:00 pm)</span>
        </td>
      </tr>
      <tr>
        <td></td>
        <td><span class="hint">(leaving time fields blank will select full day)</span></td>
      </tr>
      <tr>
        <td colspan="2"><hr style="margin:5px 0"/></td>
      </tr>
      <tr>
        <td><%= f.label 'SMS alert' %></td>
        <td><%= f.check_box :sms_alert %></td>
      </tr>
      <tr>
        <td><%= f.label 'SMS address' %></td>
        <td>
          <%= f.text_field :sms_address %>
          <span class="hint">(email address linked to your phone by your carrier eg. 6501234567@txt.att.net)</span>
        </td>        
      </tr>
      <tr>
        <td><%= f.label 'Start time' %></td>
        <td>
          <%= text_field_tag "user[sstime]", @user.sstime && l(@user.sstime, :format => :default), :size => 8 %>
          <span class="hint">(e.g. 9:00 am)</span>
        </td>
      </tr>
      <tr>
        <td><%= f.label 'End time' %></td>
        <td>
          <%= text_field_tag "user[setime]", @user.setime && l(@user.setime, :format => :default), :size => 8 %>
          <span class="hint">(e.g. 6:00 pm)</span>
        </td>
      </tr>
      <tr>
        <td></td>
        <td><span class="hint">(leaving time fields blank will select full day)</span></td>
      </tr>
      <tr>
        <td colspan="2"><hr style="margin:5px 0"/></td>
      </tr>
      <tr>
        <td><%= f.label :weekend %></td>
        <td><%= f.check_box :weekend %></td>
      </tr>
      <tr>
        <td></td>
        <td><br/><%= f.submit %></td>
      </tr>

    </table>
  </div>
  <br/>
 
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users:</h1>

<table>
  <tr align="left">
    <th>Nick</th>
    <th>Email</th>
    <th>Email-alert</th>
    <th>start</th>
    <th>end</th>
    <th>SMS Alert</th>
    <th>start</th>
    <th>end</th>
    <th>weekend</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr align="left">
    <td><%= user.nick %></td>
    <td><%= user.email %></td>
    <td><%= user.email_alert %></td>
    <td><%= user.estime %></td>
    <td><%= user.eetime %></td>
    <td><%= user.sms_alert %></td>
    <td><%= user.setime %></td>
    <td><%= user.sstime %></td>
    <td><%= user.weekend %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user_path(user), :confirm => 'Are you sure?', :method => :delete %></td>
    
    
    
  </tr>
<% end %>
</table>

<br />

app/views/users/show.html.erb
<table class="simple-nb">
  <tr><td>Nick</td>            <td><%= @user.nick %></td></tr>
  <tr><td>Email</td>           <td><%= @user.email %></td></tr>
  <tr><td colspan="2"><hr style="margin:5px 0"/></td></tr>
  
  <tr><td>Email alert:</td>    <td><%= @user.email_alert %></td></tr>
  <tr><td>start</td>           <td><%= @user.estime && l(@user.estime, :format => :default) %></td></tr>
  <tr><td>end</td>             <td><%= @user.eetime && l(@user.eetime, :format => :default) %></td></tr>
  <tr><td colspan="2"><hr style="margin:5px 0"/></td></tr>
  
  <tr><td>SMS alerts</td>      <td><%= @user.sms_alert %></td></tr>
  <tr><td>SMS address</td>      <td><%= @user.sms_address %></td></tr>
  <tr><td>start</td>           <td><%= @user.sstime && l(@user.sstime, :format => :default) %></td></tr>
  <tr><td>end</td>             <td><%= @user.setime && l(@user.setime, :format => :default) %></td></tr>
  <tr><td colspan="2"><hr style="margin:5px 0"/></td></tr>
  
  <tr><td>Weekend</td>         <td><%= @user.weekend %></td></tr>
</table>

<br>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>