config/routes.rb
Bozo::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  root :to => "dashboard#index"
  
  resources :users
  resources :articles
  resources :categories
  
  resources :stats do 
    collection do
      get :incoming_by_day
      get :closed_by_day
      get :incoming_by_hour
      get :close_time_by_day
    end
  end

  resource :dashboard, :controller => 'dashboard' do
    collection do
      get :byuser
    end
  end     

end # of routes

app/views/layouts/_header.html.erb
<div id="login-controls">
  <div class="user-right">
    <ul class="ajs-menu-bar" id="header-menu-bar">
      <li>(866) 237-8815</li>
    </ul>
  </div>
</div>
<div id="doc2">

  <div id="hd">
    <div id="logo-10gen">
      <a href="/"><img src="/images/logo_10gen.png" width="95" height="45" alt="10gen"/></a>
    </div>

    <div id="nav">
      <ul>
        <li>
          <a href="/">dashboard</a>
        </li>
        <li>
          <%= link_to "stats", stats_path %>
        </li>
        <li>
          <%= link_to "My Tickets", byuser_dashboard_path %>
        </li>
        <li>
           <% if  user_signed_in? %>
            <%= link_to "Account Settings #{current_user.email}", "/users/#{current_user.id}" %><%= link_to "Sign out", destroy_user_session_path %>
           <% else %>
             <%= link_to "Sign in", new_user_session_path %><%= link_to "Create account", new_user_registration_path %>
           <% end %>
        </li>
      </ul>
    </div>

    <div id="logo-mongodb">
      <a href="http://mongodb.org"><img src="/images/mongodb.png"></a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bozo</title>
    <%= stylesheet_link_tag :all %>
    <%= stylesheet_link_tag '10gen/jquery-ui' %>
    <%= javascript_include_tag "jquery", "jquery-ui.min", "highcharts" %>
    <%= javascript_include_tag "rails" %>
  
    <%= csrf_meta_tag %>
    
    <% if @page_auto_refresh  %>
      <META HTTP-EQUIV="REFRESH" CONTENT="30">
    <% end %>
  </head>
  
  <body style="padding:0 20px">
    <%= render 'layouts/header' %>
    <br/>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>